### ISSUE TITLE
Remove/change Starlight logo from Credit component

### ISSUE THREAD

**Issue by rrenildopereiraa** [trueberryless-org/starlight-cooler-credit#39]
It would be great if we could add a new property that would let users remove/change the default logo from the credit card. Not every user will use the banner as a credit component.

```diff
starlightCoolerCredit({
  credit: {
    title: {
      en: "Hello World",
    },
    href: "https://www.example.com/docs/",
    description: {
      en: "The quick fox jumps over the lazy dog.",
    },
+   logo: false
  },
}),
```

**Comment by trueberryless** [comment]
I have implemented the feature, which will be available in the next release.
Please notice that I chose to call the property `showImage` and it is not nested inside the credit object, but localed at the root of the config options. Please check out [the docs](https://starlight-cooler-credit.trueberryless.org/configuration/#showimage)
